- name: install default python version
  shell: >
    vxvm install python {{ python_default_version }}
  register: python_default_result

- name: capture default python location
  shell: >
    vxvm location python {{ python_default_version }}
  register: python_default_location_result

- name: create profile.d entry for python
  template: src=etc-profile-d-python dest=/etc/profile.d/default-python.sh

- name: install ansible package
  pip: name=ansible executable={{ python_default_location_result.stdout }}/bin/pip
