- name: add apt repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'

- name: add apt key
  apt_key: id="ACCC4CF8" url="https://www.postgresql.org/media/keys/ACCC4CF8.asc"

- name: install packages
  apt: pkg={{item}} state=latest update_cache=true
  environment:
    RUNLEVEL: '1'
  with_items:
    - postgresql-{{pg_version}}
    - postgresql-client-{{pg_version}}
    - postgresql-contrib-{{pg_version}}
    - postgresql-{{pg_version}}-postgis-2.1
    - libpq-dev

- name: fix permissions
  file: >
    path=/var/run/postgresql/{{ pg_version }}-main.pg_stat_tmp state=directory owner=postgres group=postgres

- name: tune postgresql.cnf
  shell: >
    echo "
      set /files/etc/postgresql/9.3/main/postgresql.conf/fsync off
      set /files/etc/postgresql/9.3/main/postgresql.conf/full_page_writes off
      set /files/etc/postgresql/9.3/main/postgresql.conf/synchronous_commit off
      save
    " | augtool

- name: create pg_hba.conf
  template: src=pg_hba.conf dest=/etc/postgresql/{{pg_version}}/main/pg_hba.conf

- name: turn ssl off
  lineinfile: >
    dest=/etc/postgresql/{{ pg_version }}/main/postgresql.conf
    regexp="{{ item }}"
    state=absent
  with_items:
    - "ssl = true"
    - "ssl_cert_file = "
    - "ssl_key_file = "

- name: create service directory
  file: path=/etc/sv/postgresql state=directory

- name: create run script
  template: src=run dest=/etc/sv/postgresql/run mode=0755
